### ISSUE TITLE
rancher2_bootstrap can not be reached

### ISSUE THREAD

**Issue by staedter** [lippertmarkus/terraform-k8s-windows-rancher#1]
Hi Markus,

I tried to get the Azure rancher cluster up and runnning but encountered this error.
![image](https://user-images.githubusercontent.com/46670623/111081158-39bc4280-8502-11eb-855a-e9e52af5465d.png)

I then used Azure IP Flow to verify that there is connectivity between my external IP and the rancher VM and that apparently is not the problem. Do you have any idea why I cannot get to Rancher vm?

![image](https://user-images.githubusercontent.com/46670623/111081288-d7177680-8502-11eb-9e95-043d4a8a4d1b.png)

**Comment by lippertmarkus** [comment]
There have been changes to the newest Rancher versions (https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/single-node-docker/#privileged-access-for-rancher-v2-5). I fixed the terraform definitions (https://github.com/lippertmarkus/terraform-k8s-windows-rancher/commit/dd2ebb88f83e8a6c5bb093e330c2291333d95101). Please do a `terraform destroy`, pull the newest version of this repo and try again.

**Comment by staedter** [comment]
That solved the issue for me. Thank you very much!


![image](https://user-images.githubusercontent.com/46670623/111176283-7c852580-85a9-11eb-9637-72694c91465f.png)
